name: deploy

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Install R dependencies
      run: |
        sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
        sudo apt-get update
        sudo apt-get install -y r-cran-irkernel libcurl4-openssl-dev r-cran-biocmanager r-bioc-geoquery
        
    - name: Setup R lib paths
      run: |
        mkdir -p /home/${USER}/.rpackages
        echo "R_LIBS=/home/${USER}/.rpackages" > /home/${USER}/.Renviron
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install python dependencies
      run: pip install -r requirements.txt
    
    - name: Build the book
      run: jupyter-book build .
        
    - name: Auth google cloud
      uses: google-github-actions/auth@v0.8.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Push to Gcloud storage bucket
      uses: google-github-actions/upload-cloud-storage@v0.10.2
      with:
        path: ./_build/html
        destination: nosi-gcloud-course
