name: deploy

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Install R dependencies
      run: |
        sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
        sudo apt-get update
        sudo apt-get install -y r-cran-irkernel libcurl4-openssl-dev r-cran-biocmanager r-bioc-geoquery r-bioc-annotationdbi r-bioc-org.hs.eg.db
        
    - name: Setup R lib paths
      run: |
        mkdir -p /home/${USER}/.rpackages
        mkdir -p /home/${USER}/.Rtmp
        echo "R_LIBS=/home/${USER}/.rpackages" >> /home/${USER}/.Renviron
        echo "TMP=/home/${USER}/.Rtmp" >> /home/${USER}/.Renviron
        echo "TEMP=/home/${USER}/.Rtmp" >> /home/${USER}/.Renviron
        echo "TMPDIR=/home/${USER}/.Rtmp" >> /home/${USER}/.Renviron
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install python dependencies
      run: pip install -r requirements.txt
    
    - name: Build the book
      run: jupyter-book build .
      
    - name: Auth google cloud
      uses: google-github-actions/auth@v0.8.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Backup old version
      run: |
        gsutil -m mv gs://${{ secrets.GCLOUD_BUCKET_ID }}/html gs://${{ secrets.GCLOUD_BUCKET_ID }}/html-`date +"%Y-%m-%d-%T"`

    - name: Push to Gcloud storage bucket
      uses: google-github-actions/upload-cloud-storage@v0.10.2
      with:
        path: ./_build/html
        destination: ${{ secrets.GCLOUD_BUCKET_ID }}
        
    - name: Auth google cloud for backup notebooks
      uses: google-github-actions/auth@v0.8.0
      with:
        credentials_json: ${{ secrets.GCLOUD_BUCKET_BACKUP_SECRET }}
    
    - name: Push repos to backup Gcloud storage bucket
      uses: google-github-actions/upload-cloud-storage@v0.10.2
      with:
        path: ./
        destination: ${{ secrets.GCLOUD_BUCKET_BACKUP_ID }}
  
  mirror-gcloud:                                       
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.GCLOUD_GIT_ADDRESS }}
          ssh_private_key: ${{ secrets.GCLOUD_GIT_PRIVATE_KEY }}
          ssh_username: ${{ secrets.GCLOUD_GIT_PRIVATE_KEY_ID }}
