name: deploy

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Install R dependencies
      run: |
        sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
        sudo apt-get update
        sudo apt-get install -y r-cran-irkernel
 
